-- MySQL Script generated by MySQL Workbench
-- Tue Feb 26 17:03:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ticket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theme` (
  `idTheme` INT NOT NULL AUTO_INCREMENT,
  `Intitule` VARCHAR(45) NULL,
  PRIMARY KEY (`idTheme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Topic` (
  `idTopic` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NULL,
  `texte` VARCHAR(45) NULL,
  `Theme_idTheme` INT NOT NULL,
  PRIMARY KEY (`idTopic`, `Theme_idTheme`),
  INDEX `fk_Topic_Theme_idx` (`Theme_idTheme` ASC),
  CONSTRAINT `fk_Topic_Theme`
    FOREIGN KEY (`Theme_idTheme`)
    REFERENCES `Theme` (`idTheme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `pseudo` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attachment` (
  `idAttachment` INT NOT NULL AUTO_INCREMENT,
  `nom_attachment` VARCHAR(45) NULL,
  `type_attachment` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `Topic_idTopic` INT NOT NULL,
  `Topic_Theme_idTheme` INT NOT NULL,
  PRIMARY KEY (`idAttachment`, `Topic_idTopic`, `Topic_Theme_idTheme`),
  INDEX `fk_Attachment_Topic1_idx` (`Topic_idTopic` ASC, `Topic_Theme_idTheme` ASC),
  CONSTRAINT `fk_Attachment_Topic1`
    FOREIGN KEY (`Topic_idTopic` , `Topic_Theme_idTheme`)
    REFERENCES `Topic` (`idTopic` , `Theme_idTheme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
